"DbUser" = "{{ db_user }}"
"DbPassword" = "{{ db_password }}"
"DbName" = "{{ db_name }}"
"DbPort" = "{{ db_port }}"
"DbHost" = "{{ actual_db_endpoint }}"
"ListenHost" = "{{ listen_host }}"
"ListenPort" = "{{ listen_port }}"