- name: Deploy web
  hosts: web
  tasks:
    - name: mkdir.
      shell: mkdir -p /www/application
      become: yes

    - name: Download and unzip file
      become: yes
      unarchive:
        src: https://github.com/servian/TechChallengeApp/releases/download/v.0.10.0/TechChallengeApp_v.0.10.0_linux64.zip
        dest: /www/application
        remote_src: yes

    - name: reconfigure
      vars:
        db_user: "{{ db_user }}"
        db_password: "{{ db_pass }}"
        db_name: postgres
        db_port: 5432
        actual_db_endpoint: "{{db_endpoint | replace(':5432','')}}"
        listen_host: "0.0.0.0"
        listen_port: 80
      template:
        dest: /www/application/dist/conf.toml
        src: templates/service.tpl
      become: yes

    - name: seed database
      shell: ./TechChallengeApp updatedb -s
      args:
        chdir: /www/application/dist
      become: yes
      
    - name: Start server
      become: yes
      shell: ./TechChallengeApp serve
      args:
        chdir: /www/application/dist

