- name: Deploy web
  hosts: web
  tasks:
    - name: get rice
      shell: GO111MODULE=off go get github.com/GeertJohan/go.rice/...
      become: yes
    - name: export path
      shell: export GOPATH=$(go env GOPATH)
      become: yes
    - name: export path2
      shell: export PATH=$PATH:$(go env GOPATH)/bin
      become: yes
    - name: change mode
      shell: chmod +x build.sh
      become: yes
    - name: reconfigure
      shell: sudo dpkg-reconfigure dash
      become: yes
    - name: build
      shell: ./build.sh
      become: yes

- name: Deploy DB
  hosts: db
  tasks:
    - name: install docker 
      shell: yum -y install docker
      become: yes
    - name: start docker
      shell: systemctl start docker
      become: yes
    - name: pull
      shell: docker pull postgres
      become: yes
    - name: run
      shell: docker run --name postgres -e POSTGRES_PASSWORD=password -d postgres
      become: yes

