name: Notes app cd pipeline

on:
  push:
    branches:
      - main
      - feature
  pull_request:
    branches:
      - main

jobs:        
  Continuous-Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: generate key pairs
        run: yes '' | ssh-keygen -N '' > /dev/null

      - name: setting-AWS-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: IaC
        run: |
          cd infra
          terraform init
          terraform apply --auto-approve
      
      - name: Configuring deploy using ansible
        run: |
          cd ansible
          cd scripts
          ./run-ansible.sh