name: Notes app cd pipeline

on:
  push:
    branches:
      - main
      - feature
  pull_request:
    branches:
      - main

jobs:        
  Continuous-Deployment:
    # if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # generating the deployer key pairs, refering to 'Servian key' created by IaC terraform.
      # if running in local and you have your keys on your machine, you dont need to reproduce this step. 
      - name: generate key pairs
        run: yes '' | ssh-keygen -N '' > /dev/null

      - name: setting-AWS-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: install make
        run: |
          sudo apt-get update
          sudo apt-get install make
          
      - name: make all-up
        run: make all-up
